"""Constants for the transactional email system."""

from __future__ import annotations

COLLECTION_EMAIL_EVENTS = "email_events"

MAX_SUBJECT_LENGTH = 200
MAX_EMAIL_ATTEMPTS = 4
RETRY_BACKOFF_SECONDS = (0, 60, 300, 1800)

EMAIL_STATUS_PENDING = "pending"
EMAIL_STATUS_SENT = "sent"
EMAIL_STATUS_FAILED = "failed"
EMAIL_STATUS_RETRYING = "retrying"
EMAIL_STATUS_SKIPPED = "skipped"

EMAIL_PROVIDER_SMTP = "smtp"
EMAIL_PROVIDER_CONSOLE = "console"
EMAIL_PROVIDER_NONE = "none"
EMAIL_PROVIDER_FAKE = "fake"

# Template keys (stable identifiers for ledger + renderer)
TEMPLATE_EMAIL_VERIFICATION = "email_verification"
TEMPLATE_PASSWORD_RESET = "password_reset"
TEMPLATE_PASSWORD_CHANGED = "password_changed"
TEMPLATE_WELCOME = "welcome"
TEMPLATE_SUBSCRIPTION_TRIAL_STARTED = "subscription_trial_started"
TEMPLATE_SUBSCRIPTION_ACTIVATED = "subscription_activated"
TEMPLATE_SUBSCRIPTION_RENEWED = "subscription_renewed"
TEMPLATE_SUBSCRIPTION_PLAN_CHANGED = "subscription_plan_changed"
TEMPLATE_SUBSCRIPTION_CANCELLATION_SCHEDULED = "subscription_cancellation_scheduled"
TEMPLATE_SUBSCRIPTION_CANCELLED = "subscription_cancelled"
TEMPLATE_SUBSCRIPTION_REACTIVATED = "subscription_reactivated"
TEMPLATE_SUBSCRIPTION_PAYMENT_FAILED = "subscription_payment_failed"
TEMPLATE_SUBSCRIPTION_EXPIRED = "subscription_expired"
TEMPLATE_QUOTE_SENT = "quote_sent"
TEMPLATE_INVOICE_SENT = "invoice_sent"
TEMPLATE_PORTAL_ACCESS = "portal_access"
TEMPLATE_QUOTE_ACCEPTED = "quote_accepted"
TEMPLATE_QUOTE_REJECTED = "quote_rejected"
TEMPLATE_QUOTE_FOLLOW_UP = "quote_follow_up"
TEMPLATE_INVOICE_FOLLOW_UP = "invoice_follow_up"
TEMPLATE_PAYMENT_RECORDED = "payment_recorded"

ALL_TEMPLATE_KEYS = frozenset(
    {
        TEMPLATE_EMAIL_VERIFICATION,
        TEMPLATE_PASSWORD_RESET,
        TEMPLATE_PASSWORD_CHANGED,
        TEMPLATE_WELCOME,
        TEMPLATE_SUBSCRIPTION_TRIAL_STARTED,
        TEMPLATE_SUBSCRIPTION_ACTIVATED,
        TEMPLATE_SUBSCRIPTION_RENEWED,
        TEMPLATE_SUBSCRIPTION_PLAN_CHANGED,
        TEMPLATE_SUBSCRIPTION_CANCELLATION_SCHEDULED,
        TEMPLATE_SUBSCRIPTION_CANCELLED,
        TEMPLATE_SUBSCRIPTION_REACTIVATED,
        TEMPLATE_SUBSCRIPTION_PAYMENT_FAILED,
        TEMPLATE_SUBSCRIPTION_EXPIRED,
        TEMPLATE_QUOTE_SENT,
        TEMPLATE_INVOICE_SENT,
        TEMPLATE_PORTAL_ACCESS,
        TEMPLATE_QUOTE_ACCEPTED,
        TEMPLATE_QUOTE_REJECTED,
        TEMPLATE_QUOTE_FOLLOW_UP,
        TEMPLATE_INVOICE_FOLLOW_UP,
        TEMPLATE_PAYMENT_RECORDED,
    }
)
