from io import BytesIO
from typing import Literal, Optional

import logging

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

logger = logging.getLogger(__name__)

LOGO_MAX_WIDTH = 45 * mm
LOGO_MAX_HEIGHT = 20 * mm

DocumentType = Literal["quote", "invoice"]

QUOTE_STATUS_LABELS = {
    "fr": {
        "draft": "Brouillon",
        "sent": "Envoyé",
        "accepted": "Accepté",
        "rejected": "Refusé",
        "expired": "Expiré",
    },
    "en": {
        "draft": "Draft",
        "sent": "Sent",
        "accepted": "Accepted",
        "rejected": "Rejected",
        "expired": "Expired",
    },
}

INVOICE_STATUS_LABELS = {
    "fr": {
        "in_progress": "En cours",
        "paid": "Payée",
        "overdue": "En retard",
        "cancelled": "Annulée",
        "draft": "En cours",
        "sent": "En cours",
    },
    "en": {
        "in_progress": "In progress",
        "paid": "Paid",
        "overdue": "Overdue",
        "cancelled": "Cancelled",
        "draft": "In progress",
        "sent": "In progress",
    },
}

LABELS = {
    "fr": {
        "quote": "DEVIS",
        "invoice": "FACTURE",
        "number": "Numéro",
        "status": "Statut",
        "date": "Date",
        "client": "Client",
        "title": "Titre",
        "amount_ht": "Total HT",
        "vat": "TVA",
        "amount_ttc": "Total TTC",
        "notes": "Notes",
        "paid_at": "Payée le",
        "generated": "Document généré par MemoryHub",
        "line_items": "Prestations",
        "col_description": "Description",
        "col_quantity": "Qté",
        "col_unit_price": "PU HT",
        "col_vat": "TVA",
        "col_discount": "Remise",
        "col_line_total": "Total HT",
        "no_discount": "—",
        "issuer": "Émetteur",
        "payment_terms": "Conditions de paiement",
        "bank_details": "Coordonnées bancaires",
        "siret": "SIRET",
        "vat": "N° TVA",
    },
    "en": {
        "quote": "QUOTE",
        "invoice": "INVOICE",
        "number": "Number",
        "status": "Status",
        "date": "Date",
        "client": "Client",
        "title": "Title",
        "amount_ht": "Total excl. VAT",
        "vat": "VAT",
        "amount_ttc": "Total incl. VAT",
        "notes": "Notes",
        "paid_at": "Paid on",
        "generated": "Document generated by MemoryHub",
        "line_items": "Line items",
        "col_description": "Description",
        "col_quantity": "Qty",
        "col_unit_price": "Unit excl. VAT",
        "col_vat": "VAT",
        "col_discount": "Discount",
        "col_line_total": "Total excl. VAT",
        "no_discount": "—",
        "issuer": "Issuer",
        "payment_terms": "Payment terms",
        "bank_details": "Bank details",
        "siret": "SIRET",
        "vat": "VAT no.",
    },
}


def _format_money(cents: int, lang: str = "fr") -> str:
    value = (cents or 0) / 100
    if lang == "fr":
        formatted = f"{value:,.2f}".replace(",", "\u00a0").replace(".", ",")
        return f"{formatted} €"
    return f"€{value:,.2f}"


def _format_date(value: Optional[str], lang: str = "fr") -> str:
    if not value:
        return "—"
    try:
        from datetime import datetime

        normalized = str(value).replace("Z", "+00:00")
        dt = datetime.fromisoformat(normalized)
        if lang == "fr":
            return dt.strftime("%d/%m/%Y")
        return dt.strftime("%Y-%m-%d")
    except ValueError:
        return str(value)


def _format_quantity(value) -> str:
    qty = float(value or 1)
    if qty == int(qty):
        return str(int(qty))
    text = f"{qty:.2f}".rstrip("0").rstrip(".")
    return text.replace(".", ",") if "," not in text else text


def _format_discount(value, lang: str) -> str:
    text = str(value or "").strip()
    return text if text else LABELS[lang]["no_discount"]


def _status_label(doc_type: DocumentType, status: str, lang: str) -> str:
    labels = QUOTE_STATUS_LABELS if doc_type == "quote" else INVOICE_STATUS_LABELS
    return labels.get(lang, labels["fr"]).get(status, status)


def _extract_line_items(data: dict) -> list:
    raw_items = data.get("lineItems")
    if not isinstance(raw_items, list):
        return []
    items = []
    for raw in raw_items:
        if not isinstance(raw, dict):
            continue
        description = str(raw.get("description") or "").strip()
        amount_ht = int(raw.get("amountHT") or 0)
        if not description or amount_ht <= 0:
            continue
        items.append(raw)
    return items


def _meta_table_style() -> TableStyle:
    return TableStyle(
        [
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#6B7280")),
            ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#111827")),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#E5E7EB")),
        ]
    )


def _build_meta_rows(doc_type: DocumentType, data: dict, labels: dict, lang: str) -> list:
    date_value = data.get("quoteDate") if doc_type == "quote" else data.get("invoiceDate")
    rows = [
        [labels["number"], data.get("number", "—")],
        [labels["status"], _status_label(doc_type, data.get("status", ""), lang)],
        [labels["date"], _format_date(date_value, lang)],
        [labels["client"], data.get("clientName", "—")],
        [labels["title"], data.get("title", "—")],
    ]
    if doc_type == "invoice" and data.get("paidAt"):
        rows.append([labels["paid_at"], _format_date(data.get("paidAt"), lang)])
    return rows


def _build_summary_rows(data: dict, labels: dict, lang: str) -> list:
    vat_rate = data.get("vatRate", 0)
    vat_amount = data.get("amountTTC", 0) - data.get("amountHT", 0)
    return [
        [labels["amount_ht"], _format_money(data.get("amountHT", 0), lang)],
        [labels["vat"], f"{vat_rate} % ({_format_money(vat_amount, lang)})"],
        [labels["amount_ttc"], _format_money(data.get("amountTTC", 0), lang)],
    ]


def _build_line_items_table(line_items: list, labels: dict, lang: str) -> Table:
    header = [
        labels["col_description"],
        labels["col_quantity"],
        labels["col_unit_price"],
        labels["col_vat"],
        labels["col_discount"],
        labels["col_line_total"],
    ]
    rows = [header]
    for line in line_items:
        rows.append(
            [
                line.get("description", ""),
                _format_quantity(line.get("quantity")),
                _format_money(int(line.get("unitPriceHT") or 0), lang),
                f"{int(line.get('vatRate') or 0)} %",
                _format_discount(line.get("discount"), lang),
                _format_money(int(line.get("amountHT") or 0), lang),
            ]
        )

    table = Table(
        rows,
        colWidths=[58 * mm, 14 * mm, 24 * mm, 16 * mm, 20 * mm, 24 * mm],
        repeatRows=1,
    )
    table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F3F4F6")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#374151")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("TEXTCOLOR", (0, 1), (-1, -1), colors.HexColor("#111827")),
                ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
                ("ALIGN", (0, 0), (0, -1), "LEFT"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#D1D5DB")),
                ("LINEBELOW", (0, 1), (-1, -1), 0.25, colors.HexColor("#E5E7EB")),
            ]
        )
    )
    return table


def _build_totals_table(data: dict, labels: dict, lang: str) -> Table:
    vat_rate = data.get("vatRate", 0)
    vat_amount = data.get("amountTTC", 0) - data.get("amountHT", 0)
    rows = [
        [labels["amount_ht"], _format_money(data.get("amountHT", 0), lang)],
        [labels["vat"], f"{vat_rate} % ({_format_money(vat_amount, lang)})"],
        [labels["amount_ttc"], _format_money(data.get("amountTTC", 0), lang)],
    ]
    table = Table(rows, colWidths=[45 * mm, 45 * mm], hAlign="RIGHT")
    table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -2), "Helvetica"),
                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#6B7280")),
                ("TEXTCOLOR", (1, 0), (1, -2), colors.HexColor("#111827")),
                ("TEXTCOLOR", (0, -1), (-1, -1), colors.HexColor("#0A2540")),
                ("TEXTCOLOR", (1, -1), (1, -1), colors.HexColor("#0A2540")),
                ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("LINEABOVE", (0, 0), (-1, 0), 0.5, colors.HexColor("#D1D5DB")),
                ("LINEBELOW", (0, 0), (-1, -2), 0.25, colors.HexColor("#E5E7EB")),
            ]
        )
    )
    return table


def _build_issuer_lines(seller: Optional[dict], labels: dict) -> list:
    if not seller:
        return []
    lines = []
    name = (seller.get("legalName") or seller.get("companyName") or "").strip()
    if name:
        lines.append(f"<b>{name}</b>")
    trade = (seller.get("tradeName") or "").strip()
    if trade and trade != name:
        lines.append(trade)
    address_parts = [
        seller.get("address"),
        " ".join(p for p in [seller.get("postalCode"), seller.get("city")] if p),
        seller.get("country"),
    ]
    for part in address_parts:
        text = (part or "").strip()
        if text:
            lines.append(text)
    if seller.get("phone"):
        lines.append(str(seller["phone"]))
    if seller.get("email"):
        lines.append(str(seller["email"]))
    if seller.get("siret"):
        lines.append(f"{labels['siret']}: {seller['siret']}")
    if seller.get("vatNumber"):
        lines.append(f"{labels['vat']}: {seller['vatNumber']}")
    return lines


def _build_logo_image(logo_bytes: bytes) -> Optional[Image]:
    try:
        image = Image(BytesIO(logo_bytes))
        intrinsic_w = float(image.imageWidth or 0)
        intrinsic_h = float(image.imageHeight or 0)
        if intrinsic_w <= 0 or intrinsic_h <= 0:
            return None

        scale = min(LOGO_MAX_WIDTH / intrinsic_w, LOGO_MAX_HEIGHT / intrinsic_h)
        image.drawWidth = intrinsic_w * scale
        image.drawHeight = intrinsic_h * scale
        image.hAlign = "LEFT"
        return image
    except Exception:
        logger.exception("Failed to build PDF logo image")
        return None


def _build_document_header(
    *,
    doc_type: DocumentType,
    data: dict,
    labels: dict,
    title_style: ParagraphStyle,
    subtitle_style: ParagraphStyle,
    logo_bytes: Optional[bytes],
) -> list:
    title = Paragraph(labels[doc_type], title_style)
    subtitle = Paragraph(data.get("number", ""), subtitle_style)

    if not logo_bytes:
        return [title, subtitle]

    logo = _build_logo_image(logo_bytes)
    if not logo:
        return [title, subtitle]

    header = Table(
        [[logo, [title, subtitle]]],
        colWidths=[LOGO_MAX_WIDTH + 5 * mm, 115 * mm],
        rowHeights=[LOGO_MAX_HEIGHT + 2 * mm],
    )
    header.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ALIGN", (0, 0), (0, 0), "LEFT"),
                ("ALIGN", (1, 0), (1, 0), "RIGHT"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    return [header]


def _build_footer_lines(seller: Optional[dict], labels: dict, lang_key: str) -> list:
    if not seller:
        return []
    lines = []
    if seller.get("paymentTerms"):
        lines.append(f"<b>{labels['payment_terms']}</b>: {seller['paymentTerms']}")
    elif seller.get("paymentDelayDays"):
        delay = int(seller.get("paymentDelayDays") or 30)
        lines.append(
            f"<b>{labels['payment_terms']}</b>: "
            + (f"Paiement à {delay} jours" if lang_key == "fr" else f"Payment within {delay} days")
        )
    if seller.get("latePenaltyRate"):
        lines.append(str(seller["latePenaltyRate"]))
    if seller.get("flatRecoveryIndemnity"):
        lines.append(str(seller["flatRecoveryIndemnity"]))
    if seller.get("iban"):
        bank_line = f"IBAN: {seller['iban']}"
        if seller.get("bic"):
            bank_line += f" — BIC: {seller['bic']}"
        if seller.get("bankName"):
            bank_line = f"{seller['bankName']} — {bank_line}"
        lines.append(f"<b>{labels['bank_details']}</b>: {bank_line}")
    return lines


def build_commercial_pdf(
    doc_type: DocumentType,
    data: dict,
    lang: str = "fr",
    seller: Optional[dict] = None,
    logo_bytes: Optional[bytes] = None,
) -> bytes:
    lang_key = "fr" if lang == "fr" else "en"
    labels = LABELS[lang_key]
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        title=data.get("number") or labels[doc_type],
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Heading1"],
        fontSize=20,
        textColor=colors.HexColor((seller or {}).get("primaryColor") or "#0A2540"),
        spaceAfter=6,
    )
    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#4B5563"),
        spaceAfter=14,
    )
    section_style = ParagraphStyle(
        "DocSection",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#374151"),
        spaceAfter=6,
        spaceBefore=4,
    )
    notes_style = ParagraphStyle(
        "DocNotes",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#374151"),
        leading=14,
    )

    line_items = _extract_line_items(data)
    meta_rows = _build_meta_rows(doc_type, data, labels, lang_key)
    meta_table = Table(meta_rows, colWidths=[45 * mm, 120 * mm])
    meta_table.setStyle(_meta_table_style())

    story = _build_document_header(
        doc_type=doc_type,
        data=data,
        labels=labels,
        title_style=title_style,
        subtitle_style=subtitle_style,
        logo_bytes=logo_bytes,
    )

    issuer_lines = _build_issuer_lines(seller, labels)
    if issuer_lines:
        story.extend(
            [
                Paragraph(f"<b>{labels['issuer']}</b>", section_style),
                Paragraph("<br/>".join(issuer_lines), notes_style),
                Spacer(1, 8),
            ]
        )

    story.append(meta_table)

    if line_items:
        story.extend(
            [
                Spacer(1, 10),
                Paragraph(f"<b>{labels['line_items']}</b>", section_style),
                _build_line_items_table(line_items, labels, lang_key),
                Spacer(1, 8),
                _build_totals_table(data, labels, lang_key),
            ]
        )
    else:
        summary_rows = _build_summary_rows(data, labels, lang_key)
        summary_table = Table(summary_rows, colWidths=[45 * mm, 120 * mm])
        summary_table.setStyle(
            TableStyle(
                [
                    ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#6B7280")),
                    ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#111827")),
                    ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
                    ("TEXTCOLOR", (1, -1), (1, -1), colors.HexColor("#0A2540")),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("LINEBELOW", (0, 0), (-1, -2), 0.25, colors.HexColor("#E5E7EB")),
                ]
            )
        )
        story.extend([Spacer(1, 4), summary_table])

    notes = (data.get("internalNotes") or "").strip()
    if notes:
        story.extend(
            [
                Spacer(1, 12),
                Paragraph(f"<b>{labels['notes']}</b>", notes_style),
                Spacer(1, 4),
                Paragraph(notes.replace("\n", "<br/>"), notes_style),
            ]
        )

    footer_lines = _build_footer_lines(seller, labels, lang_key)
    if footer_lines:
        story.extend(
            [
                Spacer(1, 12),
                Paragraph("<br/>".join(footer_lines), notes_style),
            ]
        )

    story.extend(
        [
            Spacer(1, 24),
            Paragraph(labels["generated"], subtitle_style),
        ]
    )

    doc.build(story)
    return buffer.getvalue()


def build_quote_pdf(
    quote: dict,
    lang: str = "fr",
    seller: Optional[dict] = None,
    logo_bytes: Optional[bytes] = None,
) -> bytes:
    return build_commercial_pdf("quote", quote, lang, seller=seller, logo_bytes=logo_bytes)


def build_invoice_pdf(
    invoice: dict,
    lang: str = "fr",
    seller: Optional[dict] = None,
    logo_bytes: Optional[bytes] = None,
) -> bytes:
    return build_commercial_pdf("invoice", invoice, lang, seller=seller, logo_bytes=logo_bytes)
